name: IneServerStatusPlugin
version: '1.1'
main: net.inecat.ineserverstatusplugin.IneServerStatusPlugin
api-version: '1.21'
depend: [LuckPerms]
commands:
  status:
    description: ステータスを変更します
    usage: /status [status]
  afk:
    description: AFKステータスに変更します
    usage: /afk [reason]
